//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string id { get; set; }
        public System.DateTime bookingDatetime { get; set; }
        public string bookingStatus { get; set; }
        public int propId { get; set; }
        public string Username { get; set; }
        public string PaymentId { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Property Property { get; set; }
        public virtual Student Student { get; set; }
    }
}
